---
backup_directories:
  backup:
    path: /mnt/backup
  snapshot:
    path: /mnt/backup/snapshot
  restic_repo:
    path: /mnt/storage/backups/nas-repo

backup_groups:
  restic-readers:
    gid: 9999
