---
# tasks file for owendemooy.nut-client

- name: Ensure NUT Client related packages are installed.
  ansible.builtin.apt:
    name:
      - nut-client
    state: present

- name: Change UPSMON configuration.
  ansible.builtin.lineinfile:
    path: "{{ nut_config_path }}/upsmon.conf"
    regexp: "^MONITOR.*"
    line: >-
      MONITOR {{ nut_client_ups }}@{{ nut_client_server }} 1
      {{ nut_client_username }} {{ nut_client_password }}
      {{ nut_client_type | default('secondary') }}
    state: present
    mode: "0640"
  notify: Restart nut-client

- name: Change NUT configuration.
  ansible.builtin.lineinfile:
    path: "{{ nut_config_path }}/nut.conf"
    regexp: '^MODE.+'
    line: "MODE=netclient"
    state: present
    mode: "0640"

- name: Ensure NUT Client is running (if configured).
  ansible.builtin.service:
    name: "{{ nut_client_service }}"
    state: "{{ nut_client_state }}"
    enabled: "{{ nut_client_enabled }}"
  when: not ansible_check_mode
