---
# tasks file for owendemooy.backup
- name: Ensure required packages are installed.
  ansible.builtin.apt:
    name: [restic, cron]

- name: Create Backup Readers Group
  ansible.builtin.group:
    name: "{{ item.key }}"
    state: present
    gid: "{{ item.value.gid }}"
  with_items: "{{ backup_groups | dict2items }}"

- name: Directories - Ensure required directories exist.
  ansible.builtin.file:
    path: "{{ item.value.path }}"
    state: directory
    mode: "0755"
  with_items: "{{ backup_directories | dict2items }}"

- name: Copy Backup and Restore Scripts
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: /config
    mode: "0777"

- name: Get Scripts to Update
  ansible.builtin.find:
    paths: /config
    patterns: "*.sh"
  register: update_scripts

- name: Add Restic Repo Password to Scripts
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: "^export RESTIC_PASSWORD=.*$"
    line: "export RESTIC_PASSWORD={{ restic_password }}"
    state: present
  loop: "{{ update_scripts.files }}"

- name: Ensure Schedule Task exists for Backup Job
  ansible.builtin.cron:
    name: "Host Backup"
    user: root
    weekday: 0,1,2,3,4,5,6
    minute: "0"
    hour: "4"
    job: "/config/backup.sh |& tee /tmp/backup.log"
